### ISSUE TITLE
Possible bug in 00-global.conf when running will example rsyslog

### ISSUE THREAD

**Issue by sradco** [linux-system-roles/logging#11]
I running the rsyslog role on Fedora28.

I run it with the example rsyslog vars.yaml.
```
rsyslog__enabled: true
# install example packages & config files
rsyslog__example: true
rsyslog__capabilities: [ 'network', 'remote-files', 'tls' ]
rsyslog__forward: [ '' ]
rsyslog__group: root
rsyslog__user: root
```

When looking at the defaults file I see
```
  - filename: '00-global.conf'
    comment: 'Global options'
    options: |-
      global(
        defaultNetstreamDriver="{{ rsyslog__default_netstream_driver }}"
        workDirectory="{{ rsyslog__work_dir }}"
      {% if rsyslog__pki|bool and "tls" in rsyslog__capabilities %}
        defaultNetstreamDriverCAFile="{{ rsyslog__pki_path + '/' + rsyslog__pki_realm + '/' + rsyslog__pki_ca }}"
      {%   if rsyslog__default_driver_authmode != "anon" or "network" in rsyslog__capabilities %}
        defaultNetstreamDriverCertFile="{{ rsyslog__pki_path + '/' + rsyslog__pki_realm + '/' + rsyslog__pki_crt }}"
        defaultNetstreamDriverKeyFile="{{ rsyslog__pki_path + '/' + rsyslog__pki_realm + '/' + rsyslog__pki_key }}"
      {%   endif %}
      {% endif %}
      )
```
But even though  "network" is in rsyslog__capabilities I dont see the lines
        defaultNetstreamDriverCertFile="..."
        defaultNetstreamDriverKeyFile="..."

@richm @nhosoi

**Comment by nhosoi** [comment]
Unfortunately, rsyslog__pki is not a part of example...

If you add rsyslog__pki: true as follows, then defaultNetstreamDriver* would be set up as in [1]
$ cat vars.yaml
rsyslog__enabled: true
rsyslog__example: true
_rsyslog__pki: true_
rsyslog__capabilities: [ 'network', 'remote-files', 'tls' ]
rsyslog__forward: [ '' ]
rsyslog__group: root
rsyslog__user: root

[1] # cat 00-global.conf
# Ansible managed

#
# Global options
#
global(
  defaultNetstreamDriver="gtls"
  workDirectory="/var/lib/rsyslog"
  defaultNetstreamDriverCAFile="/etc/pki/domain/CA.crt"
  defaultNetstreamDriverCertFile="/etc/pki/domain/default.crt"
  defaultNetstreamDriverKeyFile="/etc/pki/domain/default.key"
)

So, I'd think this is _not_ a bug.

**Comment by sradco** [comment]
Sorry. I missed that. Closing this issue.
