### ISSUE TITLE
rsyslog - Don't move all confs to backup  by default when rerunning rsyslog role

### ISSUE THREAD

**Issue by sradco** [linux-system-roles/logging#13]
Currently when running rsyslog role we move all conf files to a backup dir and deploy new confs.

We may want to adopt this kind of approach: https://github.com/linux-system-roles/selinux#purge-local-modifications.

That is only purge the files if requested by the user.
This should allow rerunning of the role and have it immutable.

@richm @nhosoi @nkinder

**Comment by nhosoi** [comment]
Please take a look at https://github.com/linux-system-roles/logging/pull/20?

Does "Defining rsyslog_purge_original_conf to manage pre-existing config files to keep or purge" satisfy the needs?
