### ISSUE TITLE
[RFE] Set default parameters based on the required logs user want to collect

### ISSUE THREAD

**Issue by sradco** [linux-system-roles/logging#14]
In the README we address specific use cases:
1. Viaq
2. Viaq-k8s
3. Example

I think we should use the use cases above as the supported logs to collect, along with ovirt-host and ovirt-engine and custom conf and set the rsyslog and fluentd defaults based on them. So the user will not need to configure the following vars :

- rsyslog__enabled
- rsyslog__viaq
- rsyslog__capabilities
- rsyslog__group
- rsyslog__user

But only specify the required logs.

For example:
logging_logs_list: ['viaq']

Will set in the defaults file: 
rsyslog__viaq: true
rsyslog__capabilities: [ 'viaq' ]
rsyslog__group: root
rsyslog__user: root

logging_logs_list: [’viaq-k8s’ ] or logging_logs_list: ['viaq', ’viaq-k8s’ ]

Will set in the defaults file: 
rsyslog__viaq: true
rsyslog__capabilities: [ 'viaq',’viaq-k8s’ ]
rsyslog__group: root
rsyslog__user: root

This will allow the user to set only 1 variable instead of 4.
@richm @nhosoi @pcahyna @nkinder

**Comment by nhosoi** [comment]
@sradco, if you have a concrete set of vars, we could define rsyslog_ovirt (Following your suggestion, I'm replacing __ with _ now :).  Do you happen to have such info?

**Comment by sradco** [comment]
Fixed in #27.
