### ISSUE TITLE
rsyslog__forward  - documentation is not clear enough

### ISSUE THREAD

**Issue by sradco** [linux-system-roles/logging#16]
When running the rsyslog role with the example vars.yaml
````
rsyslog__enabled: true
# install example packages & config files
rsyslog__example: true
rsyslog__capabilities: [ 'network', 'remote-files', 'tls' ]
rsyslog__forward: [ '*.info @10.10.10.1:514' ]
rsyslog__group: root
rsyslog__user: root
```

For using the rsyslog forward do we only need to set the rsyslog__forward parameter ? 

Where are the logs saved by default? This is missing from documentation.

Does it also support viaq and viaq-k8s? or are they pre set to send data only to elasticsearch?

@richm @nhosoi

**Comment by nhosoi** [comment]
This is simply using the rsyslog selector-lines...
https://www.rsyslog.com/doc/v8-stable/configuration/examples.html#selector-lines
For instance, the setting [1] would be converted to [2] in remote-forward.system.  That is, the info logs will be forwarded to rsyslog on 10.10.10.10 and the critical logs will be to 10.10.10.11 over tcp.  Please note that the installation by this ansible blindly expects rsyslog on 10.10.10.{10,11} is separately configured to receive the logs forwarded by this configuration.
[1]
`rsyslog_forward: [ '*.info @@10.10.10.10:514', '*.crit @@10.10.10.11:514' ]`
[2]
```
*.info @10.10.10.10:514
*.crit @10.10.10.11:514
```
Currently, `rsyslog_conf_remote_forward` is just in `rsyslog_default_rules` not included in `rsyslog_viaq_rules`.  The former is used by `rsyslog_example` and the latter is by `rsyslog_viaq`.  Thus, rsyslog_forward in vars.yaml is just ignored in the case of rsyslog_viaq.  (plus the suffix .remote and .system are not included in the rsyslog_viaq configuration, for now.)

**Comment by richm** [comment]
> Where are the logs saved by default? This is missing from documentation.

Which logs?  Saved where?  Not sure what you mean

entries like `*.info @10.10.10.10:514` are very brief forward statements, which only allow a couple of the most commonly used parameters.  If you want to use the `action(type="omfwd" ...)` style, you can set dozens of parameters - see https://www.rsyslog.com/doc/v8-stable/configuration/modules/omfwd.html
