### ISSUE TITLE
Property-Based Filters

### ISSUE THREAD

**Issue by Cropi** [linux-system-roles/logging#179]
Are the property-based filters supported? If yes, what is the syntax for adding them to a playbook?

In an rsyslog.conf file I would use the following:
```:msg, startswith, "somefilter" -/var/log/output.log```

Rsyslog doc: https://www.rsyslog.com/doc/v8-stable/configuration/filters.html

**Comment by nhosoi** [comment]
@Cropi, thanks for your question. Currently, logging role only supports selectors to filter messages. We are adding the property-based filters to the RFE list.

**Comment by Cropi** [comment]
Thank you :)

**Comment by nhosoi** [comment]
@Cropi, could it be possible to review https://github.com/linux-system-roles/logging/pull/182 if it satisfies your needs?

I've added an example for the property-based filter to https://github.com/linux-system-roles/logging/#standalone-configuration. Please scroll down to the 5th. Thanks.

**Comment by Cropi** [comment]
Thank you @nhosoi for creating a solution in such a short time. This is what I was looking for.

I'm closing this as resolved.
