### ISSUE TITLE
In the rsyslog README es-ops is mentioned but no explanation about it.

### ISSUE THREAD

**Issue by sradco** [linux-system-roles/logging#18]
@nhosoi  - Please add to documentation what does es-ops enabled mean.
I think it should not be part of the default installation and should be mentioned in the context of Viaq.

**Comment by nhosoi** [comment]
> Set openshift_logging_use_ops to 'True', if you have a second ES and Kibana cluster for infrastructure logs.  Defaults is 'False'.
> Will this be a good definition?

/lgtm

**Comment by nhosoi** [comment]
Added your sentences to README.md in pr/#20.
Thanks!
