### ISSUE TITLE
RELP: cert and key files should be deployed in the /etc/pki/tls folder

### ISSUE THREAD

**Issue by sopos** [linux-system-roles/logging#205]
Currently, the cert and key files are stored in _/etc/rsyslog.d_.
This is not a functional issue but the files does not get the usual selinux labels. It gets _syslog_conf_t_ which grants rsyslogd the read permissions. It is just not a good practice.

**Comment by nhosoi** [comment]
Since https://github.com/linux-system-roles/logging/pull/211 is merged, closing this issue.
