### ISSUE TITLE
[RFE] Rename rsyslog_viaq_prereq_packages,  rsyslog_viaq_packages and rsyslog_viaq_rules to be general

### ISSUE THREAD

**Issue by sradco** [linux-system-roles/logging#23]
I think we should rename rsyslog_viaq_prereq_packages and rsyslog_viaq_packages to be general.
Like : rsyslog_extra_prereq_packages and rsyslog_extra_packages.

rsyslog_viaq_rules - need to consider if we should rename it as well.

In oVirt use case for example I will need to update these list to keep the elasticsearch packages and rsyslog-mmnormalize but I don't need the other packages viaq uses for transformations (like 'rsyslog-mmjsonparse', 'rsyslog-mmkubernetes')

We can keep the default to fit viaq but only rename the variables.

@richm @nhosoi

**Comment by nhosoi** [comment]
@sradco, this is not exactly what you suggested, but your comment made me revisit the code and told me viaq-k8s modules were accidentally in viaq.  So, I moved the k8s specific module out of viaq.  Could you take a look at this pr and tell me if this satisfies your need?  Thanks!
https://github.com/linux-system-roles/logging/pull/24

**Comment by sradco** [comment]
Fixed in #24
