### ISSUE TITLE
[RFE] Update example naming to be meaningful

### ISSUE THREAD

**Issue by sradco** [linux-system-roles/logging#26]
Currently setting collection for "example" data does not reflect what logs it actually collects.
Need to update its name to be meaningful.
Depends on: [RFE] Support Copying and Splitting the log stream #9

**Comment by nhosoi** [comment]
@sradco, any suggestion?
> Need to update its name to be meaningful.

I was not sure how useful the "example" setting would be and how much we'd like to encourage people to use it...

It could be something like "basic" or "generic" or even "debops" to show our respect ;)?

**Comment by sradco** [comment]
Updated name to "debops".
Fixed in #27
