### ISSUE TITLE
[RFE] set Template, Tag, and Severity

### ISSUE THREAD

**Issue by mvc1095** [linux-system-roles/logging#271]
We forward logs to [graylog](https://www.graylog.org/) which requires us to set parameters not currently available in this role in order to extract and filter specific log messages in searches and use them in automated alerting rules. Sample configuration:

For now we are using this role plus another which creates additional files like these in /etc/rsyslog.d:

```
ruleset(name="forwardToLogServer") {
  *.* action(
    name="forwardToLogServer"
    type="omfwd"
    Target="psyslog.example.com"
    Port="514"
    Protocol="UDP"
    Template="RSYSLOG_SyslogProtocol23Format"
  )
}
```

```
input(type="imfile"
      File="/var/log/php_errors.log"
      Tag="php:"
      Severity="err"
      Ruleset="onlySendToLogServer"
)
```

**Comment by nhosoi** [comment]
@mvc1095, thank you for your feedback. We are trying to support the missing attributes you reported. Could you please review this https://github.com/linux-system-roles/logging/pull/272 to see if it satisfies your requirements?

Thanks!

**Comment by nhosoi** [comment]
@mvc1095, https://github.com/linux-system-roles/logging/pull/272 is merged to the master branch.

May we close this issue now?

**Comment by richm** [comment]
> @mvc1095, #272 is merged to the master branch.
> 
> May we close this issue now?

Please reopen if necessary
