### ISSUE TITLE
[RFE] Support for rsyslog startmsg.regex option

### ISSUE THREAD

**Issue by haetnim** [linux-system-roles/logging#284]
Our application sometimes produces a log with multi-line messages which we need to process with startmsg.regex option
e.x:
```
input(type="imfile"
      file="/var/log/php_errors.log"
      tag="php:"
      severity="err"
      startmsg.regex="^[[:digit:]]{4}(-[[:digit:]]{2}){2}(T)([[:digit:]]{2}:){2}[[:digit:]]{2}.[[:digit:]]{6}-[[:digit:]]{2}:[[:digit:]]{2}[[:space:]]"
```
)

**Comment by nhosoi** [comment]
@haetnim, thank you for the RFE.

I've submitted https://github.com/linux-system-roles/logging/pull/288 to support startmsg.regex and endmsg.regex.

Could you please review it? Thanks!

**Comment by nhosoi** [comment]
https://github.com/linux-system-roles/logging/pull/288 is merged.
Closing this issue for now.
Please reopen it if there's anything missing.
Thanks.
