### ISSUE TITLE
Should logs formatting be specific to output type?

### ISSUE THREAD

**Issue by sradco** [linux-system-roles/logging#33]
For now I'm assuming that we have single logs formatting for each input (logs_collection).

Do we want to have different logs formatting for each output type?
Example, have different Viaq formatting when outputting to Elasticsearch and another to a Kafka output and another for remote rsyslog, etc.

Alternatively, we can have a default formatting and if it should be different it can be passed to the role using the rsyslog specific parameter.
For example, in the viaq use case we have the "rsyslog_conf_viaq_formatting" .

I would assume that we don't need this functionality at this point, But I would like your opinion and to think how/if this will affect the logging role API.

@richm @nhosoi @pcahyna @nhosoi @tabowling

**Comment by richm** [comment]
> Do we want to have different logs formatting for each output type?
> Example, have different Viaq formatting when outputting to Elasticsearch and another to a Kafka output and another for remote rsyslog, etc.

typically, no - that should not be the default case - if the user wants to do something like that, they should probably provide very custom, specific rsyslog configs to do that

**Comment by sradco** [comment]
Not need at this point. Closing.
