### ISSUE TITLE
Improvement for input_files.j2 - Adding reopenOnTruncate option for rsyslog imfile module

### ISSUE THREAD

**Issue by LarryLovestein** [linux-system-roles/logging#397]
**Description**:
In our infrastructure, we utilize logrotate for managing multiple log files. However, we have encountered a known issue with rsyslog where it is unable to collect logs after logrotate due to file truncation. This issue arises because the rsyslog **imfile** module does not have the **reopenOnTruncate** option.

**Proposal**:
To address this issue, we suggest adding the reopenOnTruncate option to the input_files.j2 template. Enabling this option will allow rsyslog to reopen log files after truncation, ensuring continuous log collection even after logrotate.

`
input(
  type="imfile"
  file="{{ __rsyslog_input.input_log_path }}"
  tag="{{ __rsyslog_input.name }}"
{% if __rsyslog_input.severity is defined %}
  severity="{{ __rsyslog_input.severity }}"
{% endif %}
{% if __rsyslog_input.facility is defined %}
  facility="{{ __rsyslog_input.facility }}"
{% endif %}
{% if __rsyslog_input.startmsg_regex is defined %}
  startmsg.regex="{{ __rsyslog_input.startmsg_regex }}"
{% endif %}
{% if __rsyslog_input.endmsg_regex is defined %}
  endmsg.regex="{{ __rsyslog_input.endmsg_regex }}"
{% endif %}
{% if __rsyslog_input.reopen_on_truncate is defined %}
  endmsg.regex="{{ __rsyslog_input.reopen_on_truncate }}"
{% endif %}
)
{{ lookup('template', 'input_template.j2') }}
`

**Comment by richm** [comment]
fixed by https://github.com/linux-system-roles/logging/pull/398
