### ISSUE TITLE
[RFE] Add tags to inputs based on the output name

### ISSUE THREAD

**Issue by sradco** [linux-system-roles/logging#42]
We need to add a tag to the inputs, so we can later filter the records based on the output name and direct then to the correct output.

@pcahyna

**Comment by sradco** [comment]
@jvymazal

**Comment by jvymazal** [comment]
Generally I think all (or at least all widely used) inputs in rsyslog have the `(tag="whatever you need")` option which you can use to mark the input with the tag you need (just mind that basic tags are limited to 32 chars in length), then you can use `if syslogtag == "whatever you need" then action()` for conditioning the outputs.

**Comment by sradco** [comment]
Thank you. Should I use, if syslogtag == "something" or if tag == "something"

**Comment by jvymazal** [comment]
It is bit counter-intuitive but although you are using `tag=""` in the inputs, the actual property you filter with is `syslogtag`.

**Comment by nhosoi** [comment]
@sradco, did you have a chance to see my email "rsyslog: switching outputs based on the tags" sent to you on the 14th of Dec?  It has a small sample conf.  HTH...

**Comment by sradco** [comment]
Hi,

@jvymazal , How do I "tag" the data coming from the "imjournal" input?

Thank you,

**Comment by jvymazal** [comment]
Unfortunately in case of imjournal you have to tag the message sooner as message from journald already contains a tag so it is just taken over. 

If you really need to do it in rsyslog you will have to overwrite the journal tag via some `set` statement or similar.
