### ISSUE TITLE
When to cleanup an output

### ISSUE THREAD

**Issue by sradco** [linux-system-roles/logging#43]
We tag each new log with its output name.
Then we create the outputs configurations in a way that the data if filtered based on the output name it was tagged with.
This allows controlling the data flow.

Currently we decided that the default of a logs_collection configuration is "present", which means that the configuration files for this logs_collection will be removed only when it is marked as "state: absent"

In case the user reruns the role with different logs_collections. There is an option that a specific output will not be in use anymore in the current run, but it is still used in previous configurations that still exists and where not removed.
 
How do we know if an output is not used anymore and remove the configurations for it?

One option is to decide that each run should include *all* needed logs_collections and if a collection is not in the logs_collection, then its configurations should be removed (implicit "state:absent").

@pcahyna @tabowling @richm @nhosoi

**Comment by nhosoi** [comment]
> One option is to decide that each run should include all needed logs_collections and if a collection is not in the logs_collection, then its configurations should be removed (implicit "state:absent").

+1
