### ISSUE TITLE
When using rsyslog_purge_original_conf true it does not delete the sub directories

### ISSUE THREAD

**Issue by sradco** [linux-system-roles/logging#44]
When using rsyslog_purge_original_conf true, the files are deleted from the sub-directories, but the directory itself is not deleted.

**Comment by nhosoi** [comment]
Thanks, @sradco.  I could reproduce the problem.

https://github.com/linux-system-roles/logging/pull/48

**Comment by sradco** [comment]
Due to fix  #50 , this issue is no longer relevant. Closing.
