### ISSUE TITLE
Include meta information

### ISSUE THREAD

**Issue by dawud** [linux-system-roles/logging#58]
As of now, pulling this role using `ansible-galaxy` fails with:

```
 [WARNING]: - linux-system-roles-logging was NOT installed successfully: this
role does not appear to have a meta/main.yml file.
```

Please include a `meta/main.yml` file to prevent this.

**Comment by sradco** [comment]
@dawud I'm not sure what license should I use here.
Do you know?

**Comment by dawud** [comment]
It's up to the main contributor, I suppose.
Other linux-system-roles seem to be using either MIT, BSD-3-Clause or GPL-3.0+.
