### ISSUE TITLE
Integration with journald/auditd

### ISSUE THREAD

**Issue by Klaas-** [linux-system-roles/logging#62]
are there any plans to also integrate with journald/auditd to enable remote logging and/or general configuration or would you see this as independent roles?

**Comment by sradco** [comment]
We separate input data and output.
So, If you mean to add support output logs to remote rsyslog , then yes. We plan to add it to the optional outputs. 
Also, for input we can add journald/auditd as an additional inputs, there should be no problem.
I see this as part of this role.
