### ISSUE TITLE
[RFE] rsyslog - need to add a generic elasticsearch output

### ISSUE THREAD

**Issue by nhosoi** [linux-system-roles/logging#8]
Comment by @richm :
> actually, this elasticsearch output is specific to viaq rsyslog__conf_viaq_elasticsearch - so it should be specific to viaq - we'll have to add another elasticsearch output that is more generic in the future

**Comment by nhosoi** [comment]
@sradco, 
This is the first cut for this issue (e.g., no doc has been added yet).
Do you think this satisfies the needs in RHV?
https://github.com/linux-system-roles/logging/pull/20/commits/29e3353d2860574f9c69baf16f9d380cb73996f6

**Comment by sradco** [comment]
I see you updated rsyslog_elastcsearch to rsyslog_elastcsearch_viaq. I think this RFE is still relevant since this does not handle generics elasticsearch output.
@nhosoi @richm

**Comment by sradco** [comment]
Fixed in PR #27.
